# Generated by Django 4.2.25 on 2025-10-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sport', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=100, unique=True)),
                ('emoji', models.CharField(default='🏃', help_text='Emoji icon representing the sport', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Brief description of the sport')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sport is available for selection')),
                ('category', models.CharField(choices=[('team', 'Team Sport'), ('individual', 'Individual Sport'), ('racket', 'Racket Sport'), ('water', 'Water Sport'), ('combat', 'Combat Sport'), ('fitness', 'Fitness & Gym'), ('outdoor', 'Outdoor Activity'), ('other', 'Other')], default='other', help_text='Category of the sport', max_length=50)),
                ('popularity_score', models.IntegerField(default=0, help_text='Score used for sorting popular sports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
                'ordering': ['-popularity_score', 'name'],
            },
        ),
    ]
