# Generated by Django 4.2.25 on 2025-10-29 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('criteria', models.CharField(help_text="e.g., 'punctuality', 'first_session', etc.", max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
            ],
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_present', models.BooleanField(default=False, help_text='User confirmed attendance')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '👍'), (0, '👎')], null=True)),
                ('punctual', models.BooleanField(default=False)),
                ('good_partner', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated recap or encouragement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='user_sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='ParticipantFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '👍'), (0, '👎')], null=True)),
                ('teamwork', models.BooleanField(default=False, help_text='Was a good teammate?')),
                ('punctual', models.BooleanField(default=False, help_text='Was on time?')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_participant_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_feedbacks', to='user_sessions.session')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_participant_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'author', 'target')},
            },
        ),
    ]
