# Generated by Django 4.2.25 on 2025-10-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='avatars/'),
        ),
    ]
