# Generated by Django 4.2.25 on 2025-10-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_display_name_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='marital_status',
        ),
    ]
