# Generated by Django 4.2.25 on 2025-10-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('', 'Select Country'), ('TN', 'Tunisia'), ('DZ', 'Algeria'), ('MA', 'Morocco'), ('EG', 'Egypt'), ('LY', 'Libya'), ('FR', 'France'), ('DE', 'Germany'), ('GB', 'United Kingdom'), ('US', 'United States'), ('CA', 'Canada'), ('IT', 'Italy'), ('ES', 'Spain'), ('PT', 'Portugal'), ('BE', 'Belgium'), ('NL', 'Netherlands'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('TR', 'Turkey'), ('XX', 'Other')], default='TN', help_text='Required', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short bio or description'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City name', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', help_text='Required', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', help_text='Required', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', help_text='Required', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Contact phone number', max_length=20),
        ),
    ]
