# Generated by Django 4.2.25 on 2025-10-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('users', '0006_remove_userprofile_address_remove_userprofile_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interested_sports',
            field=models.ManyToManyField(blank=True, help_text='Sports the user is interested in', related_name='interested_users', to='core.sport'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sports',
            field=models.TextField(blank=True, default='[]', help_text='JSON array of selected sports (deprecated - use interested_sports)'),
        ),
    ]
