# Generated by Django 4.2.25 on 2025-10-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_change_availability_to_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_tags',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated personality tags/labels (2-3 tags)', null=True),
        ),
    ]
