# Generated by Django 4.2.25 on 2025-10-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sport_type',
            field=models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('swimming', 'Swimming'), ('running', 'Running'), ('cycling', 'Cycling'), ('gym', 'Gym / Fitness'), ('yoga', 'Yoga'), ('badminton', 'Badminton'), ('table_tennis', 'Table Tennis'), ('cricket', 'Cricket'), ('baseball', 'Baseball'), ('golf', 'Golf'), ('hiking', 'Hiking'), ('skateboarding', 'Skateboarding'), ('dance', 'Dance'), ('martial_arts', 'Martial Arts'), ('other', 'Other')], max_length=20),
        ),
    ]
